server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: job-service
              uri: lb://job-service
              predicates:
                - Path=/api/v1/jobs/**
            - id: candidate-service
              uri: lb://candidate-service
              predicates:
                - Path=/api/v1/candidates/**
            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/api/v1/notifications
            - id: application-service
              uri: lb://application-service
              predicates:
                - Path=/api/v1/applications/**
#              filters:
#                - args: RequestRateLimiter
#                  name:
#                    redis-rate-limiter.replenishRate: 10   # tokens added per second
#                    redis-rate-limiter.burstCapacity: 20   # max tokens in the bucket
#                    redis-rate-limiter.requestedTokens: 1  # tokens consumed per request
#                    key-resolver: "#{@ipKeyResolver}"
#                    deny-empty-key: true
#                    empty-key-status-code: 403

            - id: cv-parse-service
              uri: lb://cv-parse-service
              predicates:
                - Path=/api/v1/cvparses/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Địa chỉ Eureka Server
    fetch-registry: true      # Tải registry về local cache
    register-with-eureka: true  # Đăng ký bản thân vào registry
  instance:
    prefer-ip-address: true    # Dùng IP thay hostname - quan trọng trong Docker
    lease-renewal-interval-in-seconds: 10   # Heartbeat mỗi 10s (dev)
    lease-expiration-duration-in-seconds: 30  # Expiry sau 30s không có heartbeat
